# Generated by Django 5.2.16 on 2026-09-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_skill_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.ImageField(blank=True, help_text='Skill icon image (replaces icon)', null=True, upload_to='skills/'),
        ),
    ]
